### ISSUE TITLE
On smaller screens, content goes off page

### ISSUE THREAD

**Issue by zrh4** [CCondeluci/HSDeckAssistant-CS1520#4]
On smaller screens, content on the index page & deckbuilder pages goes off the bottom of the page. ---There is no vertical scrollbar to use, either.

Chromebook resolution: 1366 x 768
![issue1](https://cloud.githubusercontent.com/assets/14111745/11122948/69658eca-892b-11e5-8486-7867268222b7.png)
![issue2](https://cloud.githubusercontent.com/assets/14111745/11122947/69658470-892b-11e5-9081-ced68baf7a1f.png)

**Comment by zrh4** [comment]
It's not just on my chromebook: my work laptop has the same resolution & same issues

**Comment by CCondeluci** [comment]
Fixed in responsiveness update
